### ISSUE TITLE
Interop with MGit

### ISSUE THREAD

**Issue by ShalokShalom** [go-gitea/git#109]
https://github.com/maks/MGit/issues/248

**Comment by bkcsoft** [comment]
I have no clue what that is about. The comments about gitea having an "incompatible git implementation" is plain wrong since we literaly  `exec(git)`. If you have anything specific you want fixed feel free to reopen, until then this issue doesn't say anything at all 🙄

**Comment by pstrotmann** [comment]
cannot open git-receive-pack
still get this error, which means push to github impossible
